name: Webpacker
version: 1.1.7
description: 'The power of Webpack inside Statamic.'
url: 'https://github.com/jimblue/statamic-addon-webpacker'
developer: jimblue
developer_url: 'https://github.com/jimblue'
commercial: true
