sections:

  server:
    display: Dev Server
    fields:
      proxy:
        type: text
        display: Proxy
        placeholder: 'e.g. http(s)://domain_name.test'
        instructions: The php server domain where Statamic is running
        validate: required
      https:
        type: toggle
        display: HTTPS
        instructions: Toggle HTTPS on server with HTTP2
        default: false
      ssl_certs:
        type: toggle
        display: SSL certificates
        instructions: Toggle SSL certificates to prevent browser security message
        default: false
        show_when:
          https: true

  webbrowser:
    display: Web Browser
    fields:
      open_website:
        type: toggle
        display: Open website
        instructions: Open website on web browser after initialization
        default: true
      dev_browser:
        type: select
        display: Web browser
        instructions: The web browser to use
        default: os_default
        options:
            os_default: Default
            'google chrome': Google Chrome
            safari: Safari
            firefox: Firefox
            opera: Opera
            ie: Internet Explorer
      console_display:
        type: checkboxes
        display: Console
        instructions: How coding errors, linting errors and webpack runtime errors must be display in the web browser
        options:
          error: display errors
          warning: display warnings
      overlay_display:
        type: checkboxes
        display: Overlay
        instructions: How coding errors, linting errors and webpack runtime errors must be display in the web browser
        options:
          error: display errors
          warning: display warnings
      overlay_theme:
        type: select
        display: Overlay theme
        instructions: The overlay theme for the the web browser overlay
        default: light
        options:
            light: Light
            dark: Dark

  tools:
    display: Tools
    fields:
      open_browsersyncui:
        type: toggle
        display: BrowserSync UI
        instructions: Open BrowserSync UI on default web browser after initialization
        default: true
      open_bundleanalyzer:
        type: toggle
        display: BundleAnalyzer
        instructions: Open BundleAnalyzer on default web browser after initialization
        default: true

  notifications:
    display: Notifications
    fields:
      os_notify:
        type: toggle
        display: OS Notification
        instructions: Toggle OS notification
        default: true
      os_notify_sound:
        type: toggle
        display: OS Notification sound
        instructions: Toggle OS notification sound
        default: true
      browsersync_notify:
        type: toggle
        display: BrowserSync notification
        instructions: Toggle BrowserSync status popup
        default: true

  files:
    display: Files
    fields:
      output_folder:
        type: text
        display: Output folder
        placeholder: 'Assets folder name (e.g. dist)'
        instructions: 'Be carefull, if this is empty, assets will be ouput in your {{ theme }} root. Any js / css / images / fonts folders will be overwriteen!'
      dev_sourcemaps:
        type: select
        display: Development source maps
        instructions: Refer to webpack documentation to choose your settings https://webpack.js.org/configuration/devtool/
        default: cheap-module-eval-source-map
        options:
          (none): (none)
          eval: eval
          eval-source-map: eval-source-map
          cheap-eval-source-map: cheap-eval-source-map
          cheap-module-eval-source-map: cheap-module-eval-source-map
      prod_sourcemaps:
        type: select
        display: Production source maps
        instructions: Refer to webpack documentation to choose your settings https://webpack.js.org/configuration/devtool/
        default: (none)
        options:
          (none): (none)
          source-map: source-map
          hidden-source-map: hidden-source-map
          nosources-source-map: nosources-source-map

  splitting:
    display: Code Splitting
    fields:
      manifest:
        type: toggle
        display: Manifest
        instructions: Move webpack runtime code to a separate manifest.js file in order to support long-term caching. This will avoid hash recreation for other files when only application files are changed
        default: true
      vendors:
        type: toggle
        display: Vendors
        instructions: Move node_modules vendors to a separate vendors.js file in order to support long-term caching. This will avoid hash recreation for other files when only application files are changed
        default: true
      commons:
        type: toggle
        display: Commons
        instructions: Move modules used in multiple assets to a separate commons.js file in order to support long-term caching. This will avoid hash recreation for other files when only application files are changed
        default: true
